// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Home": {
    "language": "Language",
    "hello": "Hello",
    "changeLanguage": "Change Language"
  },
  "LocaleLayout": {
    "title": "next-intl example"
  },
  "Manifest": {
    "name": "next-intl example"
  }
};
export default messages;